README.rst
docker/Dockerfile
make_rpm
plugins/make_deb
plugins/make_rpm
service/make_deb
service/make_rpm

FOGL-3522 organization name fixes

---

docker/Dockerfile

FOGL-3574 fledge directory name fixes in dockerfile

---

make_rpm

FOGL-3579: Renamed rpmbuild to RPM

---

make_rpm

FOGL-3579: Fixed the path of BUILDROOT

---

plugins/make_deb

FOGL-4085 additional libs support added for debian packaging

---

packages/Debian/aarch64/DEBIAN/control

FOGL:4136 Added automake and python3-dev in Depends for aarch64

---

packages/Debian/common/DEBIAN/postrm
packages/Debian/common/DEBIAN/preinst

Signed-off-by: Stefano <stefano@dianomic.com>

FOGL-4174: fix a problem of deleted files during the upgrade

---

plugins/make_rpm

FOGL-3206 RPM packaging name fixes if plugin_package_name env is set in plugin

---

service/make_deb
service/make_rpm

FOGL-4867 notification delivery & rule plugins empty directories added with notification service packaging

---

.gitignore
others/README.rst
others/make_deb
others/packages/DEBIAN/control
others/packages/DEBIAN/postinst
others/scripts/mqtt/Description
others/scripts/mqtt/VERSION
others/scripts/mqtt/requirements.sh
plugins/make_deb

Contents for **fledge-mqtt**
```
$ sudo dpkg -c /home/aj/Development/fledge-pkg/others/archive/DEBIAN/x86_64/fledge-mqtt-1.8.2-x86_64.deb 
drwxr-xr-x aj/aj             0 2021-01-11 17:52 ./
drwxr-xr-x aj/aj             0 2021-01-11 17:52 ./usr/
drwxr-xr-x aj/aj             0 2021-01-11 17:52 ./usr/local/
drwxr-xr-x aj/aj             0 2021-01-11 17:52 ./usr/local/lib/
-rw-r--r-- aj/aj        244832 2021-01-11 17:52 ./usr/local/lib/libpaho-mqtt3a.so.1.3.7
-rw-r--r-- aj/aj        244712 2021-01-11 17:52 ./usr/local/lib/libpaho-mqtt3a.so.1.3.8
-rw-r--r-- aj/aj        276472 2021-01-11 17:52 ./usr/local/lib/libpaho-mqtt3as.so.1.3.7
-rw-r--r-- aj/aj        276360 2021-01-11 17:52 ./usr/local/lib/libpaho-mqtt3as.so.1.3.8
-rw-r--r-- aj/aj …
```

FOGL-4771 additional libraries centralized scripts added in other directory

---

.gitignore
others/make_deb
others/scripts/gcp/Description
others/scripts/gcp/VERSION
others/scripts/gcp/requirements.sh
plugins/make_deb

http://archives.fledge-iot.org/fixes/FOGL-4900
`Fledge%20Custom%20Jobs/job/fledge_packages_installation_ub1804/318` - Installation of packages are also fine

FOGL-4900 fledge-gcp common package

---

others/make_rpm
others/packages/RPM/SPECS/others.spec
others/scripts/mqtt/requirements.sh
plugins/make_rpm

FOGL-4923 additional library packages support added for RPM platform

---

packages/RPM/SPECS/fledge.spec

FOGL-5506: Skip start of fledge when package is upgraded

---

docker/latest/Dockerfile.centos7

FOGL-5142: Dockerfile for CentOS 7

---

docker/Dockerfile.centos7
docker/Dockerfile.ubuntu1804
docker/Dockerfile.ubuntu2004
docker/README.md

Make based Dockerfiles for ubuntu20 and centos7

---

packages/RPM/SPECS/fledge.spec

FOGL-5975 YUM task support added when we update the core fledge & gui package

---

make_deb
make_rpm
others/make_deb
others/make_rpm
others/packages/RPM/SPECS/others.spec
packages/RPM/SPECS/fledge.spec
plugins/make_deb
plugins/make_rpm
plugins/packages/RPM/SPECS/plugin.spec
service/make_deb
service/make_rpm
service/packages/RPM/SPECS/service.spec

Sample Packages:
nightly - http://archives.fledge-iot.org/fixes/FOGL-5932/
1.9.2 - http://archives.fledge-iot.org/fixes/FOGL-5932-1.9.2/
Sample output of installed **nightly** packages on Ubuntu 18
```
ubuntu@ip-10-0-0-94:~$ sudo apt show fledge
Package: fledge
Version: 1.9.2-66-gaf46173be
Priority: optional
Section: devel
Maintainer: Dianomic Systems, Inc. <info@dianomic.com>
Installed-Size: unknown
Depends: autoconf,curl,libtool,libboost-dev,libboost-system-dev,libboost-thread-dev,libpq-dev,python3-dev,python3-pip,python3-setuptools,sqlite3,sudo,krb5-user,libcurl4-openssl-dev
Conflicts:
Homepage: http://www.dianomic.com
Download-Size: 2595 kB
APT-Manual-Installed: yes
APT-Sources: http://archives.fledge-iot.org/fixes/FOGL-5932/ubuntu1804/x86_64  Packages
Description: Fledge, the open …
```

FOGL-5932: Add git info in packages

---

others/make_rpm
plugins/make_rpm
service/make_rpm

Fix condition when "git describe" command fails

---

docker/latest/Dockerfile.ubuntu1804-arm64

Dockerfile for arm64

---

service/make_deb

FOGL-6130 service make_deb fixes

---

packages/RPM/SPECS/fledge.spec

Install pip package of numpy instead of yum package

---

make_rpm

Signed-off-by: Innovative-ashwin <sinha.ashwini111@gmail.com>

Fledge-Pkg changes for postgres13 upgrade(FOGL-6348)

---

packages/Debian/aarch64/DEBIAN/control
packages/Debian/armv7l/DEBIAN/control
packages/Debian/x86_64/DEBIAN/control
packages/RPM/SPECS/fledge.spec

numpy issue is resolved with this PR on all platforms except CentOS, I have filed a JIRA FOGL-6344 for same.

FOGL-5665: Added numpy as a dependent package of fledge package

---

make_deb
make_rpm
others/make_deb
others/make_rpm
plugins/make_deb
plugins/make_rpm
service/make_deb
service/make_rpm

FOGL-6315: Handle the condition when creating packages from tag

---

plugins/make_rpm
plugins/packages/RPM/SPECS/plugin.spec

FOGL-4103 additional libs support added in RPM plugins packaging

---

others/make_deb

FOGL-6422 iec additional library path fixes for bullseye

---

others/scripts/s2opcua/S2OPC.patch

patch file updated for S2OPCUA Toolkit

---

others/scripts/s2opcua/requirements.sh

Packaging scripts updated for S2OPCUA

---

others/scripts/s2opcua/requirements.sh

FOGL-6775 S2OPC source directory points to S2OPC_Toolkit_1.2.0 release

---

plugins/make_deb
plugins/packages/DEBIAN/postinst

Debian extras install script handling added for C-based plugins

---

packages/Debian/common/DEBIAN/postinst

pip3 command is replaced with python3 -m pip

---

plugins/make_deb
plugins/make_rpm

See the version info for C-type plugins with non-release builds
```
// 20221114114753
// http://100.26.161.46:8081/fledge/plugins/installed
{
"plugins": [
{
"name": "http_north",
"type": "north",
"description": "HTTP North Plugin",
"version": "2.0.1-1-g3b0e57d",
"installedDirectory": "north/http_north",
"packageName": "fledge-north-http-north"
},
{
"name": "OMF",
"type": "north",
"description": "PI Server North C Plugin",
"version": "2.0.1",
"installedDirectory": "north/OMF",
"packageName": ""
},
{
"name": "httpc",
"type": "north",
"description": "HTTP North C Plugin, support primary and secondary destinations with failover",
"version": "2.0.1-1-g09cb126",
"installedDirectory": "north/httpc",
"packageName": "fledge-north-httpc"
},
{
"name": "sinusoid",
"type": "south",
"description": …
```

FOGL-7078 commit hash count added in C plugins as well with non-release builds

---

packages/RPM/SPECS/fledge.spec

Changes in this PR is done so that installation of fledge through RPM package can be done properly on CentOS Stream 9.

FOGL-7084 CentOS Stream 9 support

---

packages/RPM/SPECS/fledge.spec

… chkconfig package as dependency and other fixes

FOGL-7257 CentOS Stream9 Spec support fixes and its package installation

---

packages/Debian/common/DEBIAN/postinst

Work with https://github.com/fledge-iot/fledge/pull/1545

FOGL-9331 pip install package handling added to support for python 3.11 or higher

---

make_deb
make_rpm

FOGL-9476 Updated options in the Fledge Debian and RPM package script
